Ricetta ^-- Primo
Ricetta ^-- Secondo
Ricetta ^-- Dolce

class Ricetta {
    +nome : str
    +tempo_preparazione : float
    +ingredienti : list
    +difficolta : float
    +disponibile : bool
    __
    +tempo_totale_preparazione(self) 
    +verifica_disponibilita_ingredienti(self)
    +stampa_ricette(self)
    +verifica_ingredienti(self)

    +get_nome(self)
    +set_nome(self)
    
    +get_tempo_preparazione(self)
    +set_tempo_preparazione(self)

    +get_ingredienti(self)
    +set_ingredienti(self)

    +get_difficolta(self)
    +set_difficolta(self)

    +get_disponiblie(self)
    +set_disponiblie(self)

    +aggiungi_ingredienti(self)
}

class Primo {
    +tipo_pasta : str
    +sugo : str
    __
    +get_pasta(self)
    +set_pasta(self)
    
    +get_sugo(self)
    +set_sugo(self)

}

class Secondo {
    +tipo_carne : str
    +cottura : str
    __
    +get_tipo_carne(self)
    +set_tipo_carne(self)

    +get_cottura(self)
    +set_cottura(self)


}

class Dolce {
    +zucchero : float
    +tipo_dolce : str
    __
    +get_zucchero(self)
    +set_zucchero(self)

    +get_tipo_dolce(self)
    +set_tipo_dolce(self)
}